# Generated by Django 4.1.3 on 2022-11-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0003_alter_class_attack_alter_class_defense_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="attack",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="class",
            name="defense",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="class",
            name="life",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="class",
            name="mana",
            field=models.PositiveIntegerField(),
        ),
    ]
