# Generated by Django 4.1.3 on 2022-11-07 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        ('classes', '0006_alter_class_attack_alter_class_defense_and_more'),
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('level', models.PositiveIntegerField()),
                ('silver', models.PositiveIntegerField()),
                ('gold', models.PositiveIntegerField()),
                ('char_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char_class', to='classes.class')),
                ('equipments', models.ManyToManyField(related_name='equipments', to='equipments.equipment')),
                ('skills', models.ManyToManyField(related_name='skills', to='skills.skill')),
            ],
        ),
    ]
