# Generated by Django 4.1.3 on 2022-11-09 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='attributes',
        ),
    ]
