# Generated by Django 4.1.3 on 2022-11-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
