# Generated by Django 4.1.3 on 2022-11-08 21:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('life', models.PositiveIntegerField()),
                ('atack', models.PositiveIntegerField()),
                ('defense', models.PositiveIntegerField()),
                ('mana', models.PositiveIntegerField()),
            ],
        ),
    ]
