# Generated by Django 4.1.3 on 2022-11-08 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='atack',
            new_name='attack',
        ),
    ]
