# Generated by Django 4.1.3 on 2022-11-09 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_remove_character_attributes'),
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='character',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='char_attribute', to='characters.character'),
        ),
    ]
